development:
  adapter: postgresql
  encoding: unicode
  database: diquantum_development
  pool: 5
  username: postgres
  password: admin


test:
  adapter: postgresql
  encoding: unicode
  database: diquantum
  pool: 5
  username: postgres
  password: admin
